- SOBRE MIM
- opa meu nome é jackie vedois
- meu email de contato é jackie.vedois@escola.pr.gov.br 
- estou interresado em aprender a progamar novas linguagens.
- eu estou aprendendo a progamar recentemente a linguagem de JavaSript e Scratch
